### ISSUE TITLE
A list of rulesets / Hosting the default rule

### ISSUE THREAD

**Issue by mms-gianni** [everywall/ladder#12]
Do you have a good ruleset you want to share? 
Leave a link here. Ill add it to the README.md

I am looking for a person hosting the default ruleset (Here on Github under GPLv3 or MIT) . Is anyone interested in maintaining it?

**Comment by deoxykev** [comment]
What’s typically required to bypass paywalls in terms of injecting JS? Is it usually just removing banners and clearing cookies?
