### ISSUE TITLE
Idea: break rulesets out into subdirectories and separate files 

### ISSUE THREAD

**Issue by deoxykev** [everywall/ladder#32]
I think the list of rulset modifications will grow very large over time. Just check out what happened to magnolia1234's [bypass-paywalls-firefox-clean ruleset](https://gitlab.com/magnolia1234/bypass-paywalls-firefox-clean/-/blob/master/contentScript.js?ref_type=heads). There are over 1000 individual domains.

A single file would be difficult to maintain.

I propose the ability to fetch rulesets from an open directory, so that they could be organized better. 

For example:
```
rulesets
├── de
│  └── tagesspiegel-de.yaml
├── it
└── us
   └── nytimes.yaml
```

**Comment by mms-gianni** [comment]
sure. 

We need to detect if it is a URL, a file, or a directory. 

And then, in the case of a directory, concatenate the files to the ruleset.

**Comment by mms-gianni** [comment]
And again! Awesome work. I'm getting a bit jealous. Your coding style is much cleaner than mine 😄 
Every function has a short description. 

I think we can start splitting the rulesfile. Do we need a separate repository?

**Comment by deoxykev** [comment]
Yes, I do think a separate repository would be good, to ensure the survivability of this project (keep the lawyers at bay). I've split them out in a PR https://github.com/everywall/ladder/pull/41, but we could put it in a new repo.
