### ISSUE TITLE
To deploy on my own VPS

### ISSUE THREAD

**Issue by owenxie-oss** [everywall/ladder#73]
I tried to deploy on my own VPS and changed the port number to 8211 (and I have already opened the firewall). But after the deployment was successful (the Docker logs show normal), I cannot open the work page by entering http://vpsaddress:8211 in the browser's address bar. When deploying with Docker, is it only possible to use port 8080?

Thx in advance

**Comment by deoxykev** [comment]
You can map ports using docker, to expose it on any port you’d like.

https://stackoverflow.com/questions/19335444/how-do-i-assign-a-port-mapping-to-an-existing-docker-container

**Comment by lakafior** [comment]
Hi, I've got the same problem. 
You need to keep variable
```
    environment:
      - PORT=8080
```
and only change line
```
    ports:
      - "8211:8080"
```

It is working now
